### ISSUE TITLE
Using with load cell

### ISSUE THREAD

**Issue by lhollyer** [rajmaniar/hx711#1]
Hi,

When I use this with a load cell (weight sensor) I get "Read from HX711: 0" - is there a way to read the load cell's values with this program?

Thanks!

**Comment by rajmaniar** [comment]
Hi There! 
Have you validated your circuit and the hx711 hook up?
If you have multi-meter and/or logic analyser (like a bus pirate, open scopt, nscope, etc) debugging a hardware issue is easier.

Is your application checking the `err` return of the `ReadData` method?

**Comment by lhollyer** [comment]
Hi again,

Turns out it was a hardware/soldering problem! 

I'm having another issue though - "Stopped reading because of: open /sys/class/gpio/gpio23/value: permission denied"

How do I fix this thanks?

**Comment by rajmaniar** [comment]
You might need to run it as root or, better yet, create a group that access to the gpio.

**Comment by lhollyer** [comment]
Running as root fixed it - thanks!!
